# Get docker for your system @ https://docs.docker.com/get-docker/
#   Docker for Linux
#   Docker Desktop for Windows / macOS
#
# Use the following commands to start the cluster
#   Starting:
#     $ docker-compose -f docker-compose-cluster.yml up
#   Deleteing all ZooKeeper sanpshots:
#     $ docker-compose -f docker-compose-cluster.yml down -v

version: '2'

services:
  zookeeper1:
    image: docker.io/zookeeper:3.7
    hostname: zoo1.zk.local
    restart: always
    ports:
      - 2181:2181
    networks:
      - nw
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1.zk.local:2888:3888;2181 server.2=zoo2.zk.local:2888:3888;2181 server.3=zoo3.zk.local:2888:3888;2181
      ALLOW_ANONYMOUS_LOGIN: yes

  zookeeper2:
    image: docker.io/zookeeper:3.7
    hostname: zoo2.zk.local
    restart: always
    ports:
      - 2182:2181
    networks:
      - nw
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1.zk.local:2888:3888;2181 server.2=zoo2.zk.local:2888:3888;2181 server.3=zoo3.zk.local:2888:3888;2181
      ALLOW_ANONYMOUS_LOGIN: yes

  zookeeper3:
    image: docker.io/zookeeper:3.7
    hostname: zoo3.zk.local
    restart: always
    ports:
      - 2183:2181
    networks:
      - nw
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1.zk.local:2888:3888;2181 server.2=zoo2.zk.local:2888:3888;2181 server.3=zoo3.zk.local:2888:3888;2181
      ALLOW_ANONYMOUS_LOGIN: yes

  # removed ZooNavigator, it did it's job
  zoonavigator:
    image: elkozmon/zoonavigator:1.1.1
    hostname: navigator.zk.local
    ports:
      - 9000:9000
    networks:
      - zookeeper
    environment:
      HTTP_PORT: 9000
      CONNECTION_ZKLOCAL1_NAME: ZooKeeper Server 1
      CONNECTION_ZKLOCAL1_CONN: zoo1.zk.local

      CONNECTION_ZKLOCAL2_NAME: ZooKeeper Server 2
      CONNECTION_ZKLOCAL2_CONN: zoo2.zk.local

      CONNECTION_ZKLOCAL3_NAME: ZooKeeper Server 3
      CONNECTION_ZKLOCAL3_CONN: zoo3.zk.local

      AUTO_CONNECT_CONNECTION_ID: ZKLOCAL1


  server0:
    image: "perezy/ledgerserver"
    hostname: "server0.local"
    ports:
      - '6667:6666'
    networks:
      - zookeeper
    env_file:
      - 'variables.env'
    environment:
      HOST_NAME: 'server0.local'

  server1:
    image: "perezy/ledgerserver"
    hostname: "server1.local"
    ports:
      - '6668:6666'
    networks:
      - zookeeper
    env_file:
      - 'variables.env'
    environment:
      HOST_NAME: 'server1.local'

#  server2:
#    image: perezy/ledgerserver
#    hostname: server2.local
#    ports:
#      - '6669:6666'
#    networks:
#      - zookeeper
#    env_file:
#      - 'variables.env'
#    environment:
#      HOST_NAME: 'server2.local'
#
#  server3:
#    image: perezy/ledgerserver
#    hostname: server3.local
#    ports:
#      - '6670:6666'
#    networks:
#      - zookeeper
#    env_file:
#      - 'variables.env'
#    environment:
#      HOST_NAME: 'server3.local'
#
#  server4:
#    image: perezy/ledgerserver
#    hostname: server4.local
#    ports:
#      - '6671:6666'
#    networks:
#      - zookeeper
#    env_file:
#      - 'variables.env'
#    environment:
#      HOST_NAME: 'server4.local'
#
#  server5:
#    image: perezy/ledgerserver
#    hostname: server5.local
#    ports:
#      - '6672:6666'
#    networks:
#      - zookeeper
#    env_file:
#      - 'variables.env'
#    environment:
#      HOST_NAME: 'server5.local'
#
#  server6:
#    image: perezy/ledgerserver
#    hostname: server6.local
#    ports:
#      - '6673:6666'
#    networks:
#      - zookeeper
#    env_file:
#      - 'variables.env'
#    environment:
#      HOST_NAME: 'server6.local'
#
#  server7:
#    image: perezy/ledgerserver
#    hostname: server7.local
#    ports:
#      - '6674:6666'
#    networks:
#      - zookeeper
#    env_file:
#      - 'variables.env'
#    environment:
#      HOST_NAME: 'server7.local'

networks:
  nw:
