# Get docker for your system @ https://docs.docker.com/get-docker/
#   Docker for Linux
#   Docker Desktop for Windows / macOS
#
# Use the following commands to start the cluster
#   Starting:
#     $ docker-compose -f docker-compose-cluster.yml up
#   Deleteing all ZooKeeper sanpshots:
#     $ docker-compose -f docker-compose-cluster.yml down -v

version: '2'

services:
  zookeeper1:
    image: docker.io/zookeeper:3.7
    hostname: zoo1.zk.local
    restart: always
    ports:
      - "2181:2181"
    networks:
      - nw
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1.zk.local:2888:3888;2181 server.2=zoo2.zk.local:2888:3888;2181 server.3=zoo3.zk.local:2888:3888;2181
      ALLOW_ANONYMOUS_LOGIN: 'yes'

  zookeeper2:
    image: docker.io/zookeeper:3.7
    hostname: zoo2.zk.local
    restart: always
    ports:
      - "2182:2181"
    networks:
      - nw
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1.zk.local:2888:3888;2181 server.2=zoo2.zk.local:2888:3888;2181 server.3=zoo3.zk.local:2888:3888;2181
      ALLOW_ANONYMOUS_LOGIN: 'yes'

  zookeeper3:
    image: docker.io/zookeeper:3.7
    hostname: zoo3.zk.local
    restart: always
    ports:
      - "2183:2181"
    networks:
      - nw
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1.zk.local:2888:3888;2181 server.2=zoo2.zk.local:2888:3888;2181 server.3=zoo3.zk.local:2888:3888;2181
      ALLOW_ANONYMOUS_LOGIN: 'yes'

  # removed ZooNavigator, it did it's job

  server0:
    image: dvir/ledgerserver
    hostname: server1.local
    ports:
      - '6667:6666'
    networks:
      - nw
    env_file:
      - 'variables.env'
    environment:
      HOST_NAME: 'server0.local'

  server1:
    image: dvir/ledgerserver
    hostname: server1.local
    ports:
      - '6667:6666'
    networks:
      - nw
    env_file:
      - 'variables.env'
    environment:
      HOST_NAME: 'server1.local'

  server2:
    image: dvir/ledgerserver
    hostname: server1.local
    ports:
      - '6667:6666'
    networks:
      - nw
    env_file:
      - 'variables.env'
    environment:
      HOST_NAME: 'server2.local'

  server3:
    image: dvir/ledgerserver
    hostname: server1.local
    ports:
      - '6667:6666'
    networks:
      - nw
    env_file:
      - 'variables.env'
    environment:
      HOST_NAME: 'server3.local'

  server4:
    image: dvir/ledgerserver
    hostname: server1.local
    ports:
      - '6667:6666'
    networks:
      - nw
    env_file:
      - 'variables.env'
    environment:
      HOST_NAME: 'server4.local'

  server5:
    image: dvir/ledgerserver
    hostname: server1.local
    ports:
      - '6667:6666'
    networks:
      - nw
    env_file:
      - 'variables.env'
    environment:
      HOST_NAME: 'server5.local'

  server6:
    image: dvir/ledgerserver
    hostname: server1.local
    ports:
      - '6667:6666'
    networks:
      - nw
    env_file:
      - 'variables.env'
    environment:
      HOST_NAME: 'server6.local'

  server7:
    image: dvir/ledgerserver
    hostname: server1.local
    ports:
      - '6667:6666'
    networks:
      - nw
    env_file:
      - 'variables.env'
    environment:
      HOST_NAME: 'server7.local'

networks:
  nw:
